version: '3.8'

services:
  postgresql_database:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mdp
